/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Creates a AuthRegister resource.
         * @description Creates a AuthRegister resource.
         */
        post: operations["api_authregister_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of CampaignSummary resources.
         * @description Retrieves the collection of CampaignSummary resources.
         */
        get: operations["api_campaigns_get_collection"];
        put?: never;
        /**
         * Creates a CampaignState resource.
         * @description Creates a CampaignState resource.
         */
        post: operations["api_campaigns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaignId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a CampaignState resource.
         * @description Retrieves a CampaignState resource.
         */
        get: operations["api_campaigns_campaignId_get"];
        put?: never;
        post?: never;
        /**
         * Removes the CampaignState resource.
         * @description Removes the CampaignState resource.
         */
        delete: operations["api_campaigns_campaignId_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaignId}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Creates a CampaignState resource.
         * @description Creates a CampaignState resource.
         */
        post: operations["api_campaigns_campaignIdadvance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaignId}/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Character resource.
         * @description Retrieves a Character resource.
         */
        get: operations["api_campaigns_campaignIdcharacters_get"];
        put?: never;
        /**
         * Creates a Character resource.
         * @description Creates a Character resource.
         */
        post: operations["api_campaigns_campaignIdcharacters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{characterId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Updates the Character resource.
         * @description Updates the Character resource.
         */
        patch: operations["api_characters_characterId_patch"];
        trace?: never;
    };
    "/api/campaigns/{campaignId}/rolls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Creates a DiceRoll resource.
         * @description Creates a DiceRoll resource.
         */
        post: operations["api_campaigns_campaignIdrolls_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dice/roll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Creates a DiceRoll resource.
         * @description Creates a DiceRoll resource.
         */
        post: operations["api_diceroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaignId}/journal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a JournalEntry resource.
         * @description Retrieves a JournalEntry resource.
         */
        get: operations["api_campaigns_campaignIdjournal_get"];
        put?: never;
        /**
         * Creates a JournalEntry resource.
         * @description Creates a JournalEntry resource.
         */
        post: operations["api_campaigns_campaignIdjournal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    api_auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Creates a user token.
         * @description Creates a user token.
         */
        post: operations["login_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaignId}/oracles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a OracleSummary resource.
         * @description Retrieves a OracleSummary resource.
         */
        get: operations["api_campaigns_campaignIdoracles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaignId}/oracles/{oracleId}/consult": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Creates a OracleSummary resource.
         * @description Creates a OracleSummary resource.
         */
        post: operations["api_campaigns_campaignIdoracles_oracleIdconsult_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaignId}/oracles/{oracleId}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Creates a OracleSummary resource.
         * @description Creates a OracleSummary resource.
         */
        post: operations["api_campaigns_campaignIdoracles_oracleIdsave_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of System resources.
         * @description Retrieves the collection of System resources.
         */
        get: operations["api_systems_get_collection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description POST /api/auth/register — public account creation returning a fresh token
         *     (contract: Auth paths). Modeled as an API Platform resource so the endpoint
         *     stays part of the generated OpenAPI contract.
         */
        AuthRegister: {
            email?: string | null;
            password?: string | null;
        };
        /**
         * @description POST /api/auth/register — public account creation returning a fresh token
         *     (contract: Auth paths). Modeled as an API Platform resource so the endpoint
         *     stays part of the generated OpenAPI contract.
         */
        "AuthRegister.RegisterOutput": {
            token?: string;
            roles?: string[];
        };
        /**
         * @description POST /api/auth/register — public account creation returning a fresh token
         *     (contract: Auth paths). Modeled as an API Platform resource so the endpoint
         *     stays part of the generated OpenAPI contract.
         */
        "AuthRegister.RegisterOutput.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            token?: string;
            roles?: string[];
        };
        /**
         * @description Full play state projection (contract CampaignState/StageView, FR-014).
         *
         *     Stage identity is the stage NAME (US1 decision): the contract's
         *     `currentStage.id` and `toStageId` fields carry the stage-name value, with
         *     `name` as denormalized display copy.
         */
        CampaignState: {
            id?: string;
            gameSystemId?: string;
            currentStage?: components["schemas"]["StageResource"] | null;
        };
        /**
         * @description Full play state projection (contract CampaignState/StageView, FR-014).
         *
         *     Stage identity is the stage NAME (US1 decision): the contract's
         *     `currentStage.id` and `toStageId` fields carry the stage-name value, with
         *     `name` as denormalized display copy.
         */
        "CampaignState.AdvanceStageInput": {
            toStageId?: string;
        };
        /**
         * @description Full play state projection (contract CampaignState/StageView, FR-014).
         *
         *     Stage identity is the stage NAME (US1 decision): the contract's
         *     `currentStage.id` and `toStageId` fields carry the stage-name value, with
         *     `name` as denormalized display copy.
         */
        "CampaignState.StartCampaignInput": {
            gameSystemId?: string;
        };
        /**
         * @description Full play state projection (contract CampaignState/StageView, FR-014).
         *
         *     Stage identity is the stage NAME (US1 decision): the contract's
         *     `currentStage.id` and `toStageId` fields carry the stage-name value, with
         *     `name` as denormalized display copy.
         */
        "CampaignState.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            id?: string;
            gameSystemId?: string;
            currentStage?: components["schemas"]["StageResource.jsonld"] | null;
        };
        /** @description Owned-campaign list row (contract CampaignSummary, FR-019). */
        CampaignSummary: {
            id?: string;
            gameSystemId?: string;
            gameSystemName?: string;
            currentStageName?: string;
            updatedAt?: string;
        };
        /** @description Owned-campaign list row (contract CampaignSummary, FR-019). */
        "CampaignSummary.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            id?: string;
            gameSystemId?: string;
            gameSystemName?: string;
            currentStageName?: string;
            updatedAt?: string;
        };
        /**
         * @description US5 player-facing character surface (contract paths /campaigns/{id}/characters,
         *     /characters/{characterId}). Sheets render from the system's structure
         *     metadata carried alongside each view; breaches answer 422 as a
         *     SheetValidationProblem with field-level violations (FR-023).
         */
        Character: {
            id?: string;
            kind?: string;
            name?: string;
            attributes?: {
                [key: string]: unknown;
            };
            validatedStructureVersion?: number;
            reviewStatus?: string;
            driftIssues?: string[];
            structureVersion?: number | null;
            structureFields?: components["schemas"]["SheetFieldEntryResource"][];
        };
        /**
         * @description US5 player-facing character surface (contract paths /campaigns/{id}/characters,
         *     /characters/{characterId}). Sheets render from the system's structure
         *     metadata carried alongside each view; breaches answer 422 as a
         *     SheetValidationProblem with field-level violations (FR-023).
         */
        "Character.SaveCharacterInput": {
            kind?: string;
            name?: string;
            attributes?: {
                [key: string]: string | null;
            } | null;
        };
        /**
         * @description US5 player-facing character surface (contract paths /campaigns/{id}/characters,
         *     /characters/{characterId}). Sheets render from the system's structure
         *     metadata carried alongside each view; breaches answer 422 as a
         *     SheetValidationProblem with field-level violations (FR-023).
         */
        "Character.SaveCharacterInput.jsonMergePatch": {
            kind?: string;
            name?: string;
            attributes?: {
                [key: string]: string | null;
            } | null;
        };
        /**
         * @description US5 player-facing character surface (contract paths /campaigns/{id}/characters,
         *     /characters/{characterId}). Sheets render from the system's structure
         *     metadata carried alongside each view; breaches answer 422 as a
         *     SheetValidationProblem with field-level violations (FR-023).
         */
        "Character.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            id?: string;
            kind?: string;
            name?: string;
            attributes?: {
                [key: string]: unknown;
            };
            validatedStructureVersion?: number;
            reviewStatus?: string;
            driftIssues?: string[];
            structureVersion?: number | null;
            structureFields?: components["schemas"]["SheetFieldEntryResource.jsonld"][];
        };
        /** @description Unprocessable entity */
        ConstraintViolation: {
            /** @default 422 */
            status: number;
            violations?: {
                /** @description The property path of the violation */
                propertyPath: string;
                /** @description The message associated with the violation */
                message: string;
                /** @description The code of the violation */
                code?: string;
                /** @description An extra hint to understand the violation */
                hint?: string;
                /** @description The serialized payload of the violation */
                payload?: {
                    [key: string]: unknown;
                };
            }[];
            readonly detail?: string;
            readonly type?: string;
            readonly title?: string | null;
            readonly instance?: string | null;
        };
        /** @description Unprocessable entity */
        "ConstraintViolation.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @default 422 */
            status: number;
            violations?: {
                /** @description The property path of the violation */
                propertyPath: string;
                /** @description The message associated with the violation */
                message: string;
                /** @description The code of the violation */
                code?: string;
                /** @description An extra hint to understand the violation */
                hint?: string;
                /** @description The serialized payload of the violation */
                payload?: {
                    [key: string]: unknown;
                };
            }[];
            readonly detail?: string;
            readonly description?: string;
            readonly type?: string;
            readonly title?: string | null;
            readonly instance?: string | null;
        };
        ConsultedEntryResource: {
            entryId?: string;
            text?: string;
        };
        "ConsultedEntryResource.jsonld": {
            entryId?: string;
            text?: string;
        };
        /**
         * @description US6 player-facing dice surface (contract /dice/roll + /campaigns/{campaignId}/rolls).
         *
         *     POST /dice/roll rolls without logging (200 result | 422 DiceNotationProblem);
         *     POST /campaigns/{campaignId}/rolls additionally appends a dice_roll journal
         *     entry (FR-029) and answers 201 with {roll, journalEntry}.
         */
        DiceRoll: {
            notation?: string;
            diceValues?: number[];
            modifier?: number;
            total?: number;
        };
        /**
         * @description US6 player-facing dice surface (contract /dice/roll + /campaigns/{campaignId}/rolls).
         *
         *     POST /dice/roll rolls without logging (200 result | 422 DiceNotationProblem);
         *     POST /campaigns/{campaignId}/rolls additionally appends a dice_roll journal
         *     entry (FR-029) and answers 201 with {roll, journalEntry}.
         */
        "DiceRoll.LoggedRollResource": {
            roll?: components["schemas"]["DiceRoll"];
            journalEntry?: components["schemas"]["JournalEntry"];
        };
        /**
         * @description US6 player-facing dice surface (contract /dice/roll + /campaigns/{campaignId}/rolls).
         *
         *     POST /dice/roll rolls without logging (200 result | 422 DiceNotationProblem);
         *     POST /campaigns/{campaignId}/rolls additionally appends a dice_roll journal
         *     entry (FR-029) and answers 201 with {roll, journalEntry}.
         */
        "DiceRoll.LoggedRollResource.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            roll?: components["schemas"]["DiceRoll.jsonld"];
            journalEntry?: components["schemas"]["JournalEntry.jsonld"];
        };
        /**
         * @description US6 player-facing dice surface (contract /dice/roll + /campaigns/{campaignId}/rolls).
         *
         *     POST /dice/roll rolls without logging (200 result | 422 DiceNotationProblem);
         *     POST /campaigns/{campaignId}/rolls additionally appends a dice_roll journal
         *     entry (FR-029) and answers 201 with {roll, journalEntry}.
         */
        "DiceRoll.RollDiceInput": {
            notation?: string;
        };
        /**
         * @description US6 player-facing dice surface (contract /dice/roll + /campaigns/{campaignId}/rolls).
         *
         *     POST /dice/roll rolls without logging (200 result | 422 DiceNotationProblem);
         *     POST /campaigns/{campaignId}/rolls additionally appends a dice_roll journal
         *     entry (FR-029) and answers 201 with {roll, journalEntry}.
         */
        "DiceRoll.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            notation?: string;
            diceValues?: number[];
            modifier?: number;
            total?: number;
        };
        /** @description A representation of common errors. */
        Error: {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
        };
        /** @description A representation of common errors. */
        "Error.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
            readonly description?: string | null;
        };
        HydraCollectionBaseSchema: components["schemas"]["HydraCollectionBaseSchemaNoPagination"] & {
            /**
             * @example {
             *       "@id": "string",
             *       "@type": "string",
             *       "first": "string",
             *       "last": "string",
             *       "previous": "string",
             *       "next": "string"
             *     }
             */
            view?: {
                /** Format: iri-reference */
                "@id"?: string;
                "@type"?: string;
                /** Format: iri-reference */
                first?: string | null;
                /** Format: iri-reference */
                last?: string | null;
                /** Format: iri-reference */
                previous?: string | null;
                /** Format: iri-reference */
                next?: string | null;
            };
        };
        HydraCollectionBaseSchemaNoPagination: {
            totalItems?: number;
            search?: {
                "@type"?: string;
                template?: string;
                variableRepresentation?: string;
                mapping?: {
                    "@type"?: string;
                    variable?: string;
                    property?: string | null;
                    required?: boolean;
                }[];
            };
        };
        HydraItemBaseSchema: {
            "@context"?: string | ({
                "@vocab": string;
                /** @enum {string} */
                hydra: "http://www.w3.org/ns/hydra/core#";
            } & {
                [key: string]: unknown;
            });
            "@id": string;
            "@type": string;
        };
        /**
         * @description Append-only journal projection (contract JournalEntry, FR-015/017).
         *
         *     Lives on the Campaigns API surface because the play loop owns it: stage
         *     ownership (FR-019) is enforced upstream in the same boundary. `stageId`
         *     carries the name-keyed identity decision (see CampaignStateResource).
         */
        JournalEntry: {
            id?: string;
            stageId?: string;
            stageName?: string;
            kind?: string;
            narrative?: string | null;
            oracleSnapshot?: {
                [key: string]: string;
            } | null;
            rollSnapshot?: {
                [key: string]: number | number[] | string;
            } | null;
            createdAt?: string;
        };
        /**
         * @description Append-only journal projection (contract JournalEntry, FR-015/017).
         *
         *     Lives on the Campaigns API surface because the play loop owns it: stage
         *     ownership (FR-019) is enforced upstream in the same boundary. `stageId`
         *     carries the name-keyed identity decision (see CampaignStateResource).
         */
        "JournalEntry.AppendNarrativeInput": {
            narrative?: string;
        };
        /**
         * @description Append-only journal projection (contract JournalEntry, FR-015/017).
         *
         *     Lives on the Campaigns API surface because the play loop owns it: stage
         *     ownership (FR-019) is enforced upstream in the same boundary. `stageId`
         *     carries the name-keyed identity decision (see CampaignStateResource).
         */
        "JournalEntry.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            id?: string;
            stageId?: string;
            stageName?: string;
            kind?: string;
            narrative?: string | null;
            oracleSnapshot?: {
                [key: string]: string;
            } | null;
            rollSnapshot?: {
                [key: string]: number | number[] | string;
            } | null;
            createdAt?: string;
        };
        /**
         * @description US4 player-facing oracle surface (contract paths /campaigns/{campaignId}/oracles*).
         *
         *     GET lists only the tables applicable to the campaign's system — its own
         *     plus global ones (FR-009); POST consult yields exactly one weighted-random
         *     result or a friendly notice payload (FR-010/FR-011).
         */
        OracleSummary: {
            oracleId?: string;
            title?: string;
            scopeType?: string;
            entryCount?: number;
        };
        /**
         * @description US4 player-facing oracle surface (contract paths /campaigns/{campaignId}/oracles*).
         *
         *     GET lists only the tables applicable to the campaign's system — its own
         *     plus global ones (FR-009); POST consult yields exactly one weighted-random
         *     result or a friendly notice payload (FR-010/FR-011).
         */
        "OracleSummary.ConsultOracleInput": {
            save?: boolean;
        };
        /**
         * @description US4 player-facing oracle surface (contract paths /campaigns/{campaignId}/oracles*).
         *
         *     GET lists only the tables applicable to the campaign's system — its own
         *     plus global ones (FR-009); POST consult yields exactly one weighted-random
         *     result or a friendly notice payload (FR-010/FR-011).
         */
        "OracleSummary.ConsultationOutcomeResource": {
            status?: string;
            entry?: components["schemas"]["ConsultedEntryResource"] | null;
            journalEntryId?: string | null;
        };
        /**
         * @description US4 player-facing oracle surface (contract paths /campaigns/{campaignId}/oracles*).
         *
         *     GET lists only the tables applicable to the campaign's system — its own
         *     plus global ones (FR-009); POST consult yields exactly one weighted-random
         *     result or a friendly notice payload (FR-010/FR-011).
         */
        "OracleSummary.ConsultationOutcomeResource.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            status?: string;
            entry?: components["schemas"]["ConsultedEntryResource.jsonld"] | null;
            journalEntryId?: string | null;
        };
        /**
         * @description US4 player-facing oracle surface (contract paths /campaigns/{campaignId}/oracles*).
         *
         *     GET lists only the tables applicable to the campaign's system — its own
         *     plus global ones (FR-009); POST consult yields exactly one weighted-random
         *     result or a friendly notice payload (FR-010/FR-011).
         */
        "OracleSummary.SaveConsultationInput": {
            text?: string;
            interpretation?: string;
        };
        /**
         * @description US4 player-facing oracle surface (contract paths /campaigns/{campaignId}/oracles*).
         *
         *     GET lists only the tables applicable to the campaign's system — its own
         *     plus global ones (FR-009); POST consult yields exactly one weighted-random
         *     result or a friendly notice payload (FR-010/FR-011).
         */
        "OracleSummary.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            oracleId?: string;
            title?: string;
            scopeType?: string;
            entryCount?: number;
        };
        SheetFieldEntryResource: {
            key?: string;
            label?: string;
            type?: string;
            requiredForPc?: boolean;
            requiredForNpc?: boolean;
            options?: string[];
        };
        "SheetFieldEntryResource.jsonld": {
            key?: string;
            label?: string;
            type?: string;
            requiredForPc?: boolean;
            requiredForNpc?: boolean;
            options?: string[];
        };
        StageActionResource: {
            kind?: string;
            toStageId?: string | null;
            toStageName?: string | null;
            prompt?: string;
        };
        "StageActionResource.jsonld": {
            kind?: string;
            toStageId?: string | null;
            toStageName?: string | null;
            prompt?: string;
        };
        StageResource: {
            id?: string;
            name?: string;
            guidance?: string;
            suggestedActions?: components["schemas"]["StageActionResource"][];
        };
        "StageResource.jsonld": {
            id?: string;
            name?: string;
            guidance?: string;
            suggestedActions?: components["schemas"]["StageActionResource.jsonld"][];
        };
        /**
         * @description Active-only system summaries shown to players (contract SystemSummary,
         *     FR-006). Read-only projection of the Rulesets Application read query.
         */
        System: {
            systemId?: string;
            name?: string;
            description?: string;
            startingStage?: string;
            openingGuidance?: string;
        };
        /**
         * @description Active-only system summaries shown to players (contract SystemSummary,
         *     FR-006). Read-only projection of the Rulesets Application read query.
         */
        "System.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            systemId?: string;
            name?: string;
            description?: string;
            startingStage?: string;
            openingGuidance?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_authregister_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new AuthRegister resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["AuthRegister"];
                "application/json": components["schemas"]["AuthRegister"];
            };
        };
        responses: {
            /** @description AuthRegister resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["AuthRegister.RegisterOutput.jsonld"];
                    "application/json": components["schemas"]["AuthRegister.RegisterOutput"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_campaigns_get_collection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CampaignSummary collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchemaNoPagination"] & {
                        member: components["schemas"]["CampaignSummary.jsonld"][];
                    };
                    "application/json": components["schemas"]["CampaignSummary"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_campaigns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new CampaignState resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["CampaignState.StartCampaignInput"];
                "application/json": components["schemas"]["CampaignState.StartCampaignInput"];
            };
        };
        responses: {
            /** @description CampaignState resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["CampaignState.jsonld"];
                    "application/json": components["schemas"]["CampaignState"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_campaigns_campaignId_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CampaignState identifier */
                campaignId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CampaignState resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["CampaignState.jsonld"];
                    "application/json": components["schemas"]["CampaignState"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_campaigns_campaignId_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CampaignState identifier */
                campaignId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CampaignState resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_campaigns_campaignIdadvance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CampaignState identifier */
                campaignId: string;
            };
            cookie?: never;
        };
        /** @description The new CampaignState resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["CampaignState.AdvanceStageInput"];
                "application/json": components["schemas"]["CampaignState.AdvanceStageInput"];
            };
        };
        responses: {
            /** @description CampaignState resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["CampaignState.jsonld"];
                    "application/json": components["schemas"]["CampaignState"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_campaigns_campaignIdcharacters_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Character identifier */
                campaignId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Character resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Character.jsonld"];
                    "application/json": components["schemas"]["Character"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_campaigns_campaignIdcharacters_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Character identifier */
                campaignId: string;
            };
            cookie?: never;
        };
        /** @description The new Character resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Character.SaveCharacterInput"];
                "application/json": components["schemas"]["Character.SaveCharacterInput"];
            };
        };
        responses: {
            /** @description Character resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Character.jsonld"];
                    "application/json": components["schemas"]["Character"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_characters_characterId_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Character identifier */
                characterId: string;
            };
            cookie?: never;
        };
        /** @description The updated Character resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Character.SaveCharacterInput.jsonMergePatch"];
                "application/json": components["schemas"]["Character.SaveCharacterInput.jsonMergePatch"];
            };
        };
        responses: {
            /** @description Character resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Character.jsonld"];
                    "application/json": components["schemas"]["Character"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_campaigns_campaignIdrolls_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description DiceRoll identifier */
                campaignId: string;
            };
            cookie?: never;
        };
        /** @description The new DiceRoll resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["DiceRoll.RollDiceInput"];
                "application/json": components["schemas"]["DiceRoll.RollDiceInput"];
            };
        };
        responses: {
            /** @description DiceRoll resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["DiceRoll.LoggedRollResource.jsonld"];
                    "application/json": components["schemas"]["DiceRoll.LoggedRollResource"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_diceroll_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new DiceRoll resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["DiceRoll.RollDiceInput"];
                "application/json": components["schemas"]["DiceRoll.RollDiceInput"];
            };
        };
        responses: {
            /** @description DiceRoll resource created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["DiceRoll.jsonld"];
                    "application/json": components["schemas"]["DiceRoll"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_campaigns_campaignIdjournal_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description JournalEntry identifier */
                campaignId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JournalEntry resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["JournalEntry.jsonld"];
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_campaigns_campaignIdjournal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description JournalEntry identifier */
                campaignId: string;
            };
            cookie?: never;
        };
        /** @description The new JournalEntry resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["JournalEntry.AppendNarrativeInput"];
                "application/json": components["schemas"]["JournalEntry.AppendNarrativeInput"];
            };
        };
        responses: {
            /** @description JournalEntry resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["JournalEntry.jsonld"];
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    login_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The login data */
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description User token created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        readonly token: string;
                    };
                };
            };
        };
    };
    api_campaigns_campaignIdoracles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description OracleSummary identifier */
                campaignId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OracleSummary resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["OracleSummary.jsonld"];
                    "application/json": components["schemas"]["OracleSummary"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_campaigns_campaignIdoracles_oracleIdconsult_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description OracleSummary identifier */
                campaignId: string;
                /** @description OracleSummary identifier */
                oracleId: string;
            };
            cookie?: never;
        };
        /** @description The new OracleSummary resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["OracleSummary.ConsultOracleInput"];
                "application/json": components["schemas"]["OracleSummary.ConsultOracleInput"];
            };
        };
        responses: {
            /** @description OracleSummary resource created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["OracleSummary.ConsultationOutcomeResource.jsonld"];
                    "application/json": components["schemas"]["OracleSummary.ConsultationOutcomeResource"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_campaigns_campaignIdoracles_oracleIdsave_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description OracleSummary identifier */
                campaignId: string;
                /** @description OracleSummary identifier */
                oracleId: string;
            };
            cookie?: never;
        };
        /** @description The new OracleSummary resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["OracleSummary.SaveConsultationInput"];
                "application/json": components["schemas"]["OracleSummary.SaveConsultationInput"];
            };
        };
        responses: {
            /** @description OracleSummary resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["OracleSummary.ConsultationOutcomeResource.jsonld"];
                    "application/json": components["schemas"]["OracleSummary.ConsultationOutcomeResource"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_systems_get_collection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchemaNoPagination"] & {
                        member: components["schemas"]["System.jsonld"][];
                    };
                    "application/json": components["schemas"]["System"][];
                };
            };
        };
    };
}
